// src/pages/Programs.tsx
import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import {
  BookOpen,
  Briefcase,
  Shield,
  Users,
  Heart,
  Award,
  Clock,
  MapPin,
  Calendar,
  ArrowRight,
  CheckCircle,
  Target,
  TrendingUp,
} from "lucide-react";

const Programs = () => {
  const [selectedCategory, setSelectedCategory] = useState("all");

  const programCategories = [
    { id: "all", name: "All Programs", icon: Heart },
    { id: "education", name: "Education", icon: BookOpen },
    { id: "career", name: "Career Development", icon: Briefcase },
    { id: "health", name: "Health & Wellness", icon: Shield },
    { id: "leadership", name: "Leadership", icon: Award },
  ];

  const programs = [
    {
      id: 1,
      title: "Scholarship Program",
      category: "education",
      description:
        "Full and partial scholarships for women pursuing higher education in STEM, business, and social sciences.",
      duration: "4 years",
      participants: "500+ annually",
      location: "Global",
      features: [
        "Full tuition coverage",
        "Monthly stipend",
        "Mentorship support",
        "Career placement assistance",
      ],
      outcomes: [
        "95% graduation rate",
        "85% employed within 6 months",
        "Average 40% salary increase",
      ],
      color: "empowerment",
    },
    {
      id: 2,
      title: "Professional Skills Training",
      category: "career",
      description:
        "Comprehensive training in digital literacy, project management, and leadership skills for career advancement.",
      duration: "6 months",
      participants: "300+ per cohort",
      location: "Online & In-person",
      features: [
        "Industry-relevant curriculum",
        "Hands-on projects",
        "Networking opportunities",
        "Job placement support",
      ],
      outcomes: [
        "98% completion rate",
        "70% promotion or job change",
        "Average 35% salary increase",
      ],
      color: "hope",
    },
    {
      id: 3,
      title: "Women's Health Initiative",
      category: "health",
      description:
        "Comprehensive healthcare access, mental health support, and wellness education programs for women and families.",
      duration: "Ongoing",
      participants: "2,000+ monthly",
      location: "15 countries",
      features: [
        "Free healthcare clinics",
        "Mental health counseling",
        "Health education workshops",
        "Community health workers",
      ],
      outcomes: [
        "50% improvement in health outcomes",
        "80% increase in health literacy",
        "24/7 support hotline",
      ],
      color: "growth",
    },
    {
      id: 4,
      title: "Leadership Development Program",
      category: "leadership",
      description:
        "Intensive leadership training for women seeking to advance to executive and board positions.",
      duration: "12 months",
      participants: "100 per year",
      location: "Major cities",
      features: [
        "Executive coaching",
        "Board readiness training",
        "Peer mentoring circles",
        "Strategic planning workshops",
      ],
      outcomes: [
        "90% achieve leadership roles",
        "250+ board appointments",
        "Executive network access",
      ],
      color: "wisdom",
    },
    {
      id: 5,
      title: "Entrepreneurship Bootcamp",
      category: "career",
      description:
        "Intensive program for women entrepreneurs to develop business skills, access funding, and launch successful ventures.",
      duration: "3 months",
      participants: "150+ per cohort",
      location: "Online",
      features: [
        "Business plan development",
        "Pitch training",
        "Investor introductions",
        "1-year mentorship",
      ],
      outcomes: [
        "200+ businesses launched",
        "$50M+ in funding raised",
        "75% still operating after 2 years",
      ],
      color: "strength",
    },
    {
      id: 6,
      title: "Digital Literacy Initiative",
      category: "education",
      description:
        "Basic to advanced digital skills training to bridge the technology gap and create new opportunities.",
      duration: "3 months",
      participants: "500+ per cohort",
      location: "Community centers",
      features: [
        "Computer basics",
        "Internet safety",
        "Online job applications",
        "Digital communication",
      ],
      outcomes: [
        "95% technology confidence",
        "60% find online employment",
        "Community tech support network",
      ],
      color: "hope",
    },
  ];

  const filteredPrograms =
    selectedCategory === "all"
      ? programs
      : programs.filter((program) => program.category === selectedCategory);

  const stats = [
    { number: "25+", label: "Active Programs", icon: Target },
    { number: "15K+", label: "Women Served", icon: Users },
    { number: "50+", label: "Countries", icon: MapPin },
    { number: "98%", label: "Success Rate", icon: TrendingUp },
  ];

  return (
    <div className="min-h-screen">
      <Header />

      {/* Hero Section */}
      <section className="hero-gradient">
        <div className="container-custom py-20 lg:py-28">
          <div className="max-w-4xl mx-auto text-center space-y-8">
            <Badge
              variant="secondary"
              className="bg-empowerment-100 text-empowerment-800 hover:bg-empowerment-200"
            >
              Our Programs
            </Badge>
            <h1 className="text-4xl lg:text-6xl font-bold leading-tight">
              Transforming Lives Through
              <span className="gradient-text"> Comprehensive Programs</span>
            </h1>
            <p className="text-xl text-gray-600 leading-relaxed max-w-3xl mx-auto">
              Our evidence-based programs are designed to address the unique
              challenges women face and provide them with the tools, resources,
              and support they need to succeed.
            </p>
          </div>
        </div>
      </section>

      {/* Program Stats */}
      <section className="py-16 bg-white">
        <div className="container-custom">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <div key={index} className="text-center space-y-4">
                <div className="w-16 h-16 bg-gradient-to-r from-empowerment-500 to-hope-500 rounded-full flex items-center justify-center mx-auto">
                  <stat.icon className="w-8 h-8 text-white" />
                </div>
                <div>
                  <div className="text-3xl lg:text-4xl font-bold text-gray-900">
                    {stat.number}
                  </div>
                  <div className="text-gray-600 font-medium">{stat.label}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Program Categories & Filters */}
      <section className="py-20 bg-gray-50">
        <div className="container-custom">
          <div className="text-center space-y-4 mb-12">
            <h2 className="text-3xl lg:text-4xl font-bold">
              Our Program Categories
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Explore our comprehensive range of programs designed to empower
              women at every stage of their journey.
            </p>
          </div>

          {/* Category Tabs */}
          <Tabs defaultValue="all" className="w-full">
            <TabsList className="grid w-full grid-cols-2 lg:grid-cols-5 mb-12">
              {programCategories.map((category) => (
                <TabsTrigger
                  key={category.id}
                  value={category.id}
                  className="flex items-center space-x-2"
                  onClick={() => setSelectedCategory(category.id)}
                >
                  <category.icon className="w-4 h-4" />
                  <span className="hidden sm:inline">{category.name}</span>
                </TabsTrigger>
              ))}
            </TabsList>

            {/* Programs Grid */}
            <TabsContent value={selectedCategory} className="space-y-8">
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
                {filteredPrograms.map((program) => (
                  <Card
                    key={program.id}
                    className="card-hover border-0 shadow-lg bg-white"
                  >
                    <CardContent className="p-8">
                      <div className="space-y-6">
                        <div
                          className={`w-16 h-16 bg-gradient-to-r from-${program.color}-500 to-${program.color}-600 rounded-xl flex items-center justify-center`}
                        >
                          {program.category === "education" && (
                            <BookOpen className="w-8 h-8 text-white" />
                          )}
                          {program.category === "career" && (
                            <Briefcase className="w-8 h-8 text-white" />
                          )}
                          {program.category === "health" && (
                            <Shield className="w-8 h-8 text-white" />
                          )}
                          {program.category === "leadership" && (
                            <Award className="w-8 h-8 text-white" />
                          )}
                        </div>

                        <div className="space-y-3">
                          <h3 className="text-xl font-bold">{program.title}</h3>
                          <p className="text-gray-600 leading-relaxed">
                            {program.description}
                          </p>
                        </div>

                        <div className="space-y-3 pt-4 border-t">
                          <div className="flex items-center text-sm text-gray-600">
                            <Clock className="w-4 h-4 mr-2" />
                            Duration: {program.duration}
                          </div>
                          <div className="flex items-center text-sm text-gray-600">
                            <Users className="w-4 h-4 mr-2" />
                            {program.participants}
                          </div>
                          <div className="flex items-center text-sm text-gray-600">
                            <MapPin className="w-4 h-4 mr-2" />
                            {program.location}
                          </div>
                        </div>

                        <div className="space-y-3">
                          <h4 className="font-semibold text-gray-900">
                            Key Features:
                          </h4>
                          <ul className="space-y-2">
                            {program.features
                              .slice(0, 3)
                              .map((feature, idx) => (
                                <li
                                  key={idx}
                                  className="flex items-center text-sm text-gray-600"
                                >
                                  <CheckCircle className="w-4 h-4 mr-2 text-growth-500" />
                                  {feature}
                                </li>
                              ))}
                          </ul>
                        </div>

                        <Button
                          className="w-full btn-primary"
                          onClick={() => {
                            // Navigate to program details or application
                          }}
                        >
                          Learn More
                          <ArrowRight className="ml-2 h-4 w-4" />
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </section>

      {/* Program Outcomes */}
      <section className="py-20 bg-white">
        <div className="container-custom">
          <div className="text-center space-y-4 mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold">
              Proven Results & Impact
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Our programs are designed with measurable outcomes in mind. Here's
              how we're making a difference in women's lives.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {programs.slice(0, 3).map((program, index) => (
              <Card
                key={index}
                className="border-0 shadow-lg bg-gradient-to-br from-gray-50 to-white"
              >
                <CardContent className="p-8">
                  <div className="space-y-6">
                    <div className="space-y-3">
                      <h3 className="text-xl font-bold">{program.title}</h3>
                      <p className="text-gray-600">Program Outcomes:</p>
                    </div>

                    <div className="space-y-3">
                      {program.outcomes.map((outcome, idx) => (
                        <div
                          key={idx}
                          className="flex items-center space-x-3 p-3 bg-white rounded-lg border"
                        >
                          <div className="w-8 h-8 bg-gradient-to-r from-growth-500 to-growth-600 rounded-full flex items-center justify-center">
                            <CheckCircle className="w-5 h-5 text-white" />
                          </div>
                          <span className="text-gray-700 font-medium">
                            {outcome}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* How to Apply */}
      <section className="py-20 bg-gray-50">
        <div className="container-custom">
          <div className="max-w-4xl mx-auto">
            <div className="text-center space-y-4 mb-16">
              <h2 className="text-3xl lg:text-4xl font-bold">
                How to Get Started
              </h2>
              <p className="text-xl text-gray-600">
                Ready to transform your life? Here's how to apply for our
                programs.
              </p>
            </div>

            <div className="grid md:grid-cols-4 gap-8">
              {[
                {
                  step: "1",
                  title: "Explore Programs",
                  description: "Browse our programs and find the best fit",
                },
                {
                  step: "2",
                  title: "Submit Application",
                  description: "Complete our online application form",
                },
                {
                  step: "3",
                  title: "Interview Process",
                  description: "Participate in our selection interview",
                },
                {
                  step: "4",
                  title: "Start Your Journey",
                  description: "Begin your transformational experience",
                },
              ].map((step, index) => (
                <div key={index} className="text-center space-y-4">
                  <div className="w-16 h-16 bg-gradient-to-r from-empowerment-500 to-hope-500 rounded-full flex items-center justify-center mx-auto">
                    <span className="text-white text-2xl font-bold">
                      {step.step}
                    </span>
                  </div>
                  <div className="space-y-2">
                    <h3 className="text-lg font-bold">{step.title}</h3>
                    <p className="text-gray-600">{step.description}</p>
                  </div>
                </div>
              ))}
            </div>

            <div className="text-center mt-12">
              <Button size="lg" className="btn-primary text-lg px-8 py-4">
                <Calendar className="mr-2 h-5 w-5" />
                Apply Now
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Call to Action */}
      <section className="py-20 bg-gradient-to-r from-empowerment-600 to-hope-600 text-white">
        <div className="container-custom text-center">
          <div className="max-w-3xl mx-auto space-y-8">
            <h2 className="text-3xl lg:text-4xl font-bold">
              Ready to Transform Your Future?
            </h2>
            <p className="text-xl opacity-90">
              Join thousands of women who have already transformed their lives
              through our programs. Your journey to empowerment starts here.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button
                size="lg"
                className="bg-white text-empowerment-600 hover:bg-gray-100 text-lg px-8 py-4"
              >
                <BookOpen className="mr-2 h-5 w-5" />
                Apply for Programs
              </Button>
              <Button
                size="lg"
                variant="outline"
                className="border-white text-white hover:bg-white/10 text-lg px-8 py-4"
              >
                Download Brochure
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Programs;

// src/app/pages/programs/programs.component.ts
import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";

@Component({
  selector: "app-programs",
  standalone: true,
  imports: [RouterLink],
  template: `
    <!-- Hero Section -->
    <section
      class="section-spacing bg-gradient-to-br from-pink-50 via-white to-rose-50"
    >
      <div class="max-w-7xl mx-auto">
        <div class="text-center max-w-4xl mx-auto">
          <h1
            class="text-3xl sm:text-4xl md:text-5xl lg:text-6xl xl:text-7xl font-bold text-gray-900 mb-4 sm:mb-6 lg:mb-8"
          >
            Our
            <span
              class="block sm:inline bg-gradient-to-r from-pink-500 via-pink-400 to-rose-400 bg-clip-text text-transparent"
              >Programs</span
            >
          </h1>
          <p
            class="text-base sm:text-lg lg:text-xl xl:text-2xl text-gray-600 leading-relaxed"
          >
            Comprehensive initiatives designed to empower women through
            education, skill development, and community support at every stage
            of their journey.
          </p>
        </div>
      </div>
    </section>

    <!-- Program Categories -->
    <section class="section-spacing bg-white">
      <div class="max-w-7xl mx-auto">
        <div class="text-center mb-10 sm:mb-12 lg:mb-16">
          <h2
            class="text-2xl sm:text-3xl lg:text-4xl xl:text-5xl font-bold text-gray-900 mb-4 lg:mb-6"
          >
            Program Categories
          </h2>
          <p
            class="text-base sm:text-lg lg:text-xl text-gray-600 max-w-3xl mx-auto"
          >
            Explore our three main program areas designed to create lasting
            change in women's lives.
          </p>
        </div>

        <div class="grid-responsive-3">
          <!-- Education & Skills -->
          <div
            class="card-responsive bg-white border-pink-100 hover:shadow-xl transform hover:-translate-y-2 transition-all duration-300 group"
          >
            <div
              class="w-16 h-16 sm:w-20 sm:h-20 lg:w-24 lg:h-24 bg-gradient-to-r from-pink-500 to-pink-400 rounded-full flex items-center justify-center mb-4 sm:mb-6 lg:mb-8 shadow-lg shadow-pink-200 group-hover:scale-110 transition-transform duration-300"
            >
              <span class="text-white text-2xl sm:text-3xl lg:text-4xl"
                >🎓</span
              >
            </div>
            <h3
              class="text-xl sm:text-2xl lg:text-3xl font-bold text-gray-900 mb-3 sm:mb-4 lg:mb-6"
            >
              Education & Skills
            </h3>
            <p
              class="text-sm sm:text-base lg:text-lg text-gray-600 mb-4 sm:mb-6 leading-relaxed"
            >
              Providing educational opportunities and skill development programs
              to help women build successful careers and achieve financial
              independence.
            </p>
            <ul class="text-gray-600 space-y-2 sm:space-y-3 mb-6 sm:mb-8">
              <li class="flex items-center text-sm sm:text-base">
                <span
                  class="mr-2 sm:mr-3"
                  style="color: white !important; filter: brightness(1.5);"
                  >💖</span
                >
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Digital
                literacy programs
              </li>
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Professional
                certification courses
              </li>
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Higher
                education scholarships
              </li>
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Vocational
                training
              </li>
            </ul>
            <a
              routerLink="/contact"
              class="text-pink-600 font-medium hover:text-pink-700 transition-colors duration-150 text-sm sm:text-base"
            >
              Learn More →
            </a>
          </div>

          <!-- Leadership Development -->
          <div
            class="card-responsive bg-white border-pink-100 hover:shadow-xl transform hover:-translate-y-2 transition-all duration-300 group"
          >
            <div
              class="w-16 h-16 sm:w-20 sm:h-20 lg:w-24 lg:h-24 bg-gradient-to-r from-pink-500 to-pink-400 rounded-full flex items-center justify-center mb-4 sm:mb-6 lg:mb-8 shadow-lg shadow-pink-200 group-hover:scale-110 transition-transform duration-300"
            >
              <span class="text-white text-2xl sm:text-3xl lg:text-4xl"
                >👥</span
              >
            </div>
            <h3
              class="text-xl sm:text-2xl lg:text-3xl font-bold text-gray-900 mb-3 sm:mb-4 lg:mb-6"
            >
              Leadership Development
            </h3>
            <p
              class="text-sm sm:text-base lg:text-lg text-gray-600 mb-4 sm:mb-6 leading-relaxed"
            >
              Cultivating the next generation of women leaders through
              mentorship, training, and opportunities to make meaningful impact.
            </p>
            <ul class="text-gray-600 space-y-2 sm:space-y-3 mb-6 sm:mb-8">
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Leadership
                workshops
              </li>
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Mentorship
                programs
              </li>
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Public
                speaking training
              </li>
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Board
                readiness programs
              </li>
            </ul>
            <a
              routerLink="/contact"
              class="text-pink-600 font-medium hover:text-pink-700 transition-colors duration-150 text-sm sm:text-base"
            >
              Learn More →
            </a>
          </div>

          <!-- Entrepreneurship -->
          <div
            class="card-responsive bg-white border-pink-100 hover:shadow-xl transform hover:-translate-y-2 transition-all duration-300 group"
          >
            <div
              class="w-16 h-16 sm:w-20 sm:h-20 lg:w-24 lg:h-24 bg-gradient-to-r from-pink-500 to-pink-400 rounded-full flex items-center justify-center mb-4 sm:mb-6 lg:mb-8 shadow-lg shadow-pink-200 group-hover:scale-110 transition-transform duration-300"
            >
              <span class="text-white text-2xl sm:text-3xl lg:text-4xl"
                >💼</span
              >
            </div>
            <h3
              class="text-xl sm:text-2xl lg:text-3xl font-bold text-gray-900 mb-3 sm:mb-4 lg:mb-6"
            >
              Entrepreneurship
            </h3>
            <p
              class="text-sm sm:text-base lg:text-lg text-gray-600 mb-4 sm:mb-6 leading-relaxed"
            >
              Supporting women entrepreneurs with the tools, knowledge, and
              network needed to build and scale successful businesses.
            </p>
            <ul class="text-gray-600 space-y-2 sm:space-y-3 mb-6 sm:mb-8">
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Business
                planning workshops
              </li>
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Access to
                microfinance
              </li>
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Networking
                events
              </li>
              <li class="flex items-center text-sm sm:text-base">
                <span class="text-pink-500 mr-2 sm:mr-3">💖</span> Incubator
                programs
              </li>
            </ul>
            <a
              routerLink="/contact"
              class="text-pink-600 font-medium hover:text-pink-700 transition-colors duration-150 text-sm sm:text-base"
            >
              Learn More →
            </a>
          </div>
        </div>
      </div>
    </section>

    <!-- Featured Programs -->
    <section class="section-spacing bg-pink-50">
      <div class="max-w-7xl mx-auto">
        <div class="text-center mb-10 sm:mb-12 lg:mb-16">
          <h2
            class="text-2xl sm:text-3xl lg:text-4xl xl:text-5xl font-bold text-gray-900 mb-4 lg:mb-6"
          >
            Featured
            <span
              class="bg-gradient-to-r from-pink-500 via-pink-400 to-rose-400 bg-clip-text text-transparent"
              >Programs</span
            >
          </h2>
          <p
            class="text-base sm:text-lg lg:text-xl text-gray-600 max-w-3xl mx-auto"
          >
            Our flagship initiatives that are making the biggest impact in
            communities around the world.
          </p>
        </div>

        <div class="space-y-12 sm:space-y-16 lg:space-y-24">
          <!-- Tech Leaders Program -->
          <div
            class="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12 xl:gap-16 items-center"
          >
            <div class="order-2 lg:order-1">
              <div class="flex items-center mb-4 sm:mb-6">
                <div
                  class="w-12 h-12 sm:w-16 sm:h-16 lg:w-20 lg:h-20 bg-gradient-to-r from-pink-500 to-pink-400 rounded-xl flex items-center justify-center mr-3 sm:mr-4 lg:mr-6 shadow-lg"
                >
                  <span class="text-white text-xl sm:text-2xl lg:text-3xl"
                    >💻</span
                  >
                </div>
                <h3
                  class="text-xl sm:text-2xl lg:text-3xl xl:text-4xl font-bold text-gray-900"
                >
                  Women in Tech Leaders
                </h3>
              </div>
              <p
                class="text-sm sm:text-base lg:text-lg text-gray-600 mb-6 sm:mb-8 leading-relaxed"
              >
                A comprehensive 12-month program designed to prepare women for
                senior technical roles in the technology industry. Participants
                receive advanced technical training, leadership development, and
                mentorship from industry executives.
              </p>
              <div class="grid grid-cols-2 gap-3 sm:gap-4 mb-6 sm:mb-8">
                <div
                  class="bg-white p-3 sm:p-4 lg:p-6 rounded-lg border border-pink-100"
                >
                  <h4
                    class="font-semibold text-gray-900 mb-1 sm:mb-2 text-sm sm:text-base"
                  >
                    Program Duration
                  </h4>
                  <p
                    class="text-pink-600 font-bold text-sm sm:text-base lg:text-lg"
                  >
                    12 months
                  </p>
                </div>
                <div
                  class="bg-white p-3 sm:p-4 lg:p-6 rounded-lg border border-pink-100"
                >
                  <h4
                    class="font-semibold text-gray-900 mb-1 sm:mb-2 text-sm sm:text-base"
                  >
                    Participants
                  </h4>
                  <p
                    class="text-pink-600 font-bold text-sm sm:text-base lg:text-lg"
                  >
                    500+ women
                  </p>
                </div>
                <div
                  class="bg-white p-3 sm:p-4 lg:p-6 rounded-lg border border-pink-100"
                >
                  <h4
                    class="font-semibold text-gray-900 mb-1 sm:mb-2 text-sm sm:text-base"
                  >
                    Success Rate
                  </h4>
                  <p
                    class="text-pink-600 font-bold text-sm sm:text-base lg:text-lg"
                  >
                    95% job placement
                  </p>
                </div>
                <div
                  class="bg-white p-3 sm:p-4 lg:p-6 rounded-lg border border-pink-100"
                >
                  <h4
                    class="font-semibold text-gray-900 mb-1 sm:mb-2 text-sm sm:text-base"
                  >
                    Locations
                  </h4>
                  <p
                    class="text-pink-600 font-bold text-sm sm:text-base lg:text-lg"
                  >
                    15 cities
                  </p>
                </div>
              </div>
              <a
                routerLink="/contact"
                class="btn-responsive text-white bg-gradient-to-r from-pink-500 to-pink-400 hover:from-pink-600 hover:to-pink-500 transform hover:scale-105 shadow-lg hover:shadow-xl"
              >
                <span style="color: white !important; filter: brightness(1.5);"
                  >💖</span
                >
                Apply Now
              </a>
            </div>
            <div class="order-1 lg:order-2 relative">
              <div
                class="relative z-10 rounded-xl sm:rounded-2xl lg:rounded-3xl overflow-hidden shadow-2xl border border-pink-100 transform hover:scale-105 transition-transform duration-300"
              >
                <img
                  src="https://images.unsplash.com/photo-1560472355-536de3962603?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
                  alt="Women in tech"
                  class="w-full h-64 sm:h-80 lg:h-96 xl:h-[28rem] object-cover"
                />
              </div>
            </div>
          </div>

          <!-- Global Entrepreneurship Initiative -->
          <div
            class="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12 xl:gap-16 items-center"
          >
            <div class="relative order-2 lg:order-1">
              <div
                class="relative z-10 rounded-xl sm:rounded-2xl lg:rounded-3xl overflow-hidden shadow-2xl border border-pink-100 transform hover:scale-105 transition-transform duration-300"
              >
                <img
                  src="https://images.unsplash.com/photo-1556761175-5973dc0f32e7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
                  alt="Women entrepreneurs"
                  class="w-full h-64 sm:h-80 lg:h-96 xl:h-[28rem] object-cover"
                />
              </div>
            </div>
            <div class="order-1 lg:order-2">
              <div class="flex items-center mb-4 sm:mb-6">
                <div
                  class="w-12 h-12 sm:w-16 sm:h-16 lg:w-20 lg:h-20 bg-gradient-to-r from-pink-500 to-pink-400 rounded-xl flex items-center justify-center mr-3 sm:mr-4 lg:mr-6 shadow-lg"
                >
                  <span class="text-white text-xl sm:text-2xl lg:text-3xl"
                    >🌍</span
                  >
                </div>
                <h3
                  class="text-xl sm:text-2xl lg:text-3xl xl:text-4xl font-bold text-gray-900"
                >
                  Global Entrepreneurship Initiative
                </h3>
              </div>
              <p
                class="text-sm sm:text-base lg:text-lg text-gray-600 mb-6 sm:mb-8 leading-relaxed"
              >
                Supporting women entrepreneurs in developing countries with
                access to capital, business training, and international market
                opportunities. This program has helped launch over 1,000
                women-led businesses globally.
              </p>
              <div class="grid grid-cols-2 gap-3 sm:gap-4 mb-6 sm:mb-8">
                <div
                  class="bg-white p-3 sm:p-4 lg:p-6 rounded-lg border border-pink-100"
                >
                  <h4
                    class="font-semibold text-gray-900 mb-1 sm:mb-2 text-sm sm:text-base"
                  >
                    Businesses Launched
                  </h4>
                  <p
                    class="text-pink-600 font-bold text-sm sm:text-base lg:text-lg"
                  >
                    1,000+
                  </p>
                </div>
                <div
                  class="bg-white p-3 sm:p-4 lg:p-6 rounded-lg border border-pink-100"
                >
                  <h4
                    class="font-semibold text-gray-900 mb-1 sm:mb-2 text-sm sm:text-base"
                  >
                    Countries
                  </h4>
                  <p
                    class="text-pink-600 font-bold text-sm sm:text-base lg:text-lg"
                  >
                    25 countries
                  </p>
                </div>
                <div
                  class="bg-white p-3 sm:p-4 lg:p-6 rounded-lg border border-pink-100"
                >
                  <h4
                    class="font-semibold text-gray-900 mb-1 sm:mb-2 text-sm sm:text-base"
                  >
                    Funding Provided
                  </h4>
                  <p
                    class="text-pink-600 font-bold text-sm sm:text-base lg:text-lg"
                  >
                    $2.5M+
                  </p>
                </div>
                <div
                  class="bg-white p-3 sm:p-4 lg:p-6 rounded-lg border border-pink-100"
                >
                  <h4
                    class="font-semibold text-gray-900 mb-1 sm:mb-2 text-sm sm:text-base"
                  >
                    Jobs Created
                  </h4>
                  <p
                    class="text-pink-600 font-bold text-sm sm:text-base lg:text-lg"
                  >
                    3,500+
                  </p>
                </div>
              </div>
              <a
                routerLink="/contact"
                class="btn-responsive text-white bg-gradient-to-r from-pink-500 to-pink-400 hover:from-pink-600 hover:to-pink-500 transform hover:scale-105 shadow-lg hover:shadow-xl"
              >
                <span style="color: white !important; filter: brightness(1.5);"
                  >💖</span
                >
                Get Started
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Call to Action -->
    <section
      class="section-spacing bg-gradient-to-r from-pink-500 to-pink-400 text-white"
    >
      <div class="max-w-4xl mx-auto text-center">
        <h2
          class="text-2xl sm:text-3xl lg:text-4xl xl:text-5xl font-bold mb-4 sm:mb-6 lg:mb-8"
        >
          Ready to Join Our Programs?
        </h2>
        <p
          class="text-base sm:text-lg lg:text-xl xl:text-2xl mb-6 sm:mb-8 lg:mb-10 opacity-90 leading-relaxed"
        >
          Whether you're looking to develop new skills, advance your career, or
          start a business, we have a program designed to help you succeed.
        </p>
        <div
          class="flex flex-col sm:flex-row gap-4 sm:gap-6 justify-center max-w-lg mx-auto"
        >
          <a
            routerLink="/contact"
            class="btn-responsive bg-white text-pink-600 hover:bg-pink-50 transform hover:scale-105 shadow-lg hover:shadow-xl"
          >
            <span style="color: white !important; filter: brightness(1.5);"
              >💖</span
            >
            Apply Now
          </a>
          <a
            routerLink="/donate"
            class="btn-responsive border-2 border-white text-white hover:bg-white hover:text-pink-600 transition-all duration-200"
          >
            Support Our Programs
          </a>
        </div>
      </div>
    </section>
  `,
})
export class ProgramsComponent {}
