// src/pages/Donate.tsx
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Checkbox } from "@/components/ui/checkbox";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import {
  Heart,
  CreditCard,
  Shield,
  Users,
  BookOpen,
  Briefcase,
  Award,
  Gift,
  Star,
  CheckCircle,
  ArrowRight,
  Lock,
} from "lucide-react";

const Donate = () => {
  const [donationType, setDonationType] = useState("one-time");
  const [amount, setAmount] = useState("");
  const [customAmount, setCustomAmount] = useState("");
  const [selectedProgram, setSelectedProgram] = useState("where-needed");

  const donationAmounts = [
    {
      value: "25",
      label: "$25",
      impact: "Provides school supplies for 1 student",
    },
    { value: "50", label: "$50", impact: "Funds 1 week of skills training" },
    {
      value: "100",
      label: "$100",
      impact: "Supports 1 woman's health program",
    },
    {
      value: "250",
      label: "$250",
      impact: "Covers 1 month of leadership training",
    },
    {
      value: "500",
      label: "$500",
      impact: "Funds a complete scholarship application",
    },
    {
      value: "1000",
      label: "$1000",
      impact: "Supports 1 woman's full program journey",
    },
  ];

  const programs = [
    {
      id: "where-needed",
      name: "Where Most Needed",
      description:
        "Allow us to direct your donation to programs with the greatest need",
      icon: Heart,
      color: "empowerment",
    },
    {
      id: "education",
      name: "Education & Scholarships",
      description:
        "Support women pursuing higher education and skill development",
      icon: BookOpen,
      color: "hope",
    },
    {
      id: "career",
      name: "Career Development",
      description: "Help women advance their careers and start businesses",
      icon: Briefcase,
      color: "growth",
    },
    {
      id: "health",
      name: "Health & Wellness",
      description: "Provide healthcare access and wellness education",
      icon: Shield,
      color: "wisdom",
    },
    {
      id: "leadership",
      name: "Leadership Training",
      description: "Develop the next generation of women leaders",
      icon: Award,
      color: "strength",
    },
  ];

  const impactExamples = [
    {
      amount: "$25",
      impact: "School supplies for one student for a semester",
      icon: BookOpen,
    },
    {
      amount: "$50",
      impact: "One week of professional skills training",
      icon: Briefcase,
    },
    {
      amount: "$100",
      impact: "Healthcare support for one woman for a month",
      icon: Shield,
    },
    {
      amount: "$250",
      impact: "Leadership workshop for 10 women",
      icon: Award,
    },
  ];

  const testimonials = [
    {
      name: "Sarah M.",
      role: "Monthly Donor",
      quote:
        "Knowing my $50/month helps women access education gives my contribution real meaning.",
      amount: "$50/month",
    },
    {
      name: "James K.",
      role: "Corporate Sponsor",
      quote:
        "Our company partnership has helped launch 50+ women-owned businesses.",
      amount: "$10,000/year",
    },
    {
      name: "Maria R.",
      role: "Individual Donor",
      quote:
        "I started small but seeing the impact made me want to give more each year.",
      amount: "$100/quarter",
    },
  ];

  return (
    <div className="min-h-screen">
      <Header />

      {/* Hero Section */}
      <section className="hero-gradient">
        <div className="container-custom py-20 lg:py-28">
          <div className="max-w-4xl mx-auto text-center space-y-8">
            <Badge
              variant="secondary"
              className="bg-empowerment-100 text-empowerment-800 hover:bg-empowerment-200"
            >
              Make a Difference Today
            </Badge>
            <h1 className="text-4xl lg:text-6xl font-bold leading-tight">
              Your Donation
              <span className="gradient-text"> Changes Lives</span>
            </h1>
            <p className="text-xl text-gray-600 leading-relaxed max-w-3xl mx-auto">
              Every contribution, no matter the size, directly impacts a woman's
              journey to empowerment. Join thousands of supporters who are
              creating lasting change worldwide.
            </p>
          </div>
        </div>
      </section>

      {/* Main Donation Section */}
      <section className="py-20 bg-white">
        <div className="container-custom">
          <div className="grid lg:grid-cols-3 gap-12">
            {/* Donation Form */}
            <div className="lg:col-span-2 space-y-8">
              <Card className="border-0 shadow-lg">
                <CardHeader>
                  <CardTitle className="text-2xl font-bold flex items-center">
                    <Heart className="mr-3 h-6 w-6 text-empowerment-600" />
                    Make Your Donation
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-8">
                  {/* Donation Type */}
                  <div className="space-y-4">
                    <Label className="text-base font-semibold">
                      Donation Type
                    </Label>
                    <RadioGroup
                      value={donationType}
                      onValueChange={setDonationType}
                      className="grid grid-cols-2 gap-4"
                    >
                      <div className="flex items-center space-x-2 p-4 border rounded-lg hover:bg-gray-50">
                        <RadioGroupItem value="one-time" id="one-time" />
                        <Label htmlFor="one-time" className="cursor-pointer">
                          One-time Donation
                        </Label>
                      </div>
                      <div className="flex items-center space-x-2 p-4 border rounded-lg hover:bg-gray-50">
                        <RadioGroupItem value="monthly" id="monthly" />
                        <Label htmlFor="monthly" className="cursor-pointer">
                          Monthly Giving
                        </Label>
                      </div>
                    </RadioGroup>
                  </div>

                  {/* Amount Selection */}
                  <div className="space-y-4">
                    <Label className="text-base font-semibold">
                      Select Amount
                    </Label>
                    <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                      {donationAmounts.map((donationAmount) => (
                        <div
                          key={donationAmount.value}
                          className={`p-4 border rounded-lg cursor-pointer transition-all hover:border-empowerment-300 ${
                            amount === donationAmount.value
                              ? "border-empowerment-500 bg-empowerment-50"
                              : "border-gray-200"
                          }`}
                          onClick={() => {
                            setAmount(donationAmount.value);
                            setCustomAmount("");
                          }}
                        >
                          <div className="text-center space-y-2">
                            <div className="text-lg font-bold">
                              {donationAmount.label}
                            </div>
                            <div className="text-xs text-gray-600">
                              {donationAmount.impact}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Custom Amount */}
                    <div className="space-y-2">
                      <Label htmlFor="custom-amount">Other Amount</Label>
                      <div className="relative">
                        <span className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500">
                          $
                        </span>
                        <Input
                          id="custom-amount"
                          type="number"
                          placeholder="Enter custom amount"
                          className="pl-8"
                          value={customAmount}
                          onChange={(e) => {
                            setCustomAmount(e.target.value);
                            setAmount("");
                          }}
                        />
                      </div>
                    </div>
                  </div>

                  {/* Program Selection */}
                  <div className="space-y-4">
                    <Label className="text-base font-semibold">
                      Support a Specific Program
                    </Label>
                    <RadioGroup
                      value={selectedProgram}
                      onValueChange={setSelectedProgram}
                      className="space-y-3"
                    >
                      {programs.map((program) => (
                        <div
                          key={program.id}
                          className="flex items-start space-x-3 p-4 border rounded-lg hover:bg-gray-50"
                        >
                          <RadioGroupItem
                            value={program.id}
                            id={program.id}
                            className="mt-1"
                          />
                          <div className="flex-1 space-y-2">
                            <div className="flex items-center space-x-2">
                              <program.icon
                                className={`w-5 h-5 text-${program.color}-600`}
                              />
                              <Label
                                htmlFor={program.id}
                                className="cursor-pointer font-semibold"
                              >
                                {program.name}
                              </Label>
                            </div>
                            <p className="text-sm text-gray-600">
                              {program.description}
                            </p>
                          </div>
                        </div>
                      ))}
                    </RadioGroup>
                  </div>

                  <Separator />

                  {/* Donor Information */}
                  <div className="space-y-6">
                    <h3 className="text-lg font-semibold">Donor Information</h3>
                    <div className="grid md:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="first-name">First Name</Label>
                        <Input id="first-name" placeholder="First name" />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="last-name">Last Name</Label>
                        <Input id="last-name" placeholder="Last name" />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="email">Email Address</Label>
                        <Input
                          id="email"
                          type="email"
                          placeholder="your@email.com"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="phone">Phone Number</Label>
                        <Input
                          id="phone"
                          type="tel"
                          placeholder="(555) 123-4567"
                        />
                      </div>
                    </div>
                  </div>

                  {/* Payment Information */}
                  <div className="space-y-6">
                    <h3 className="text-lg font-semibold flex items-center">
                      <CreditCard className="mr-2 h-5 w-5" />
                      Payment Information
                    </h3>
                    <div className="space-y-4">
                      <div className="space-y-2">
                        <Label htmlFor="card-number">Card Number</Label>
                        <Input
                          id="card-number"
                          placeholder="1234 5678 9012 3456"
                        />
                      </div>
                      <div className="grid grid-cols-3 gap-4">
                        <div className="space-y-2 col-span-2">
                          <Label htmlFor="expiry">Expiry Date</Label>
                          <Input id="expiry" placeholder="MM/YY" />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="cvv">CVV</Label>
                          <Input id="cvv" placeholder="123" />
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Optional Message */}
                  <div className="space-y-2">
                    <Label htmlFor="message">Message (Optional)</Label>
                    <Textarea
                      id="message"
                      placeholder="Share why you're supporting our mission..."
                      rows={3}
                    />
                  </div>

                  {/* Terms and Privacy */}
                  <div className="space-y-4">
                    <div className="flex items-start space-x-2">
                      <Checkbox id="newsletter" />
                      <Label htmlFor="newsletter" className="text-sm">
                        I would like to receive updates about the impact of my
                        donation
                      </Label>
                    </div>
                    <div className="flex items-start space-x-2">
                      <Checkbox id="terms" />
                      <Label htmlFor="terms" className="text-sm">
                        I agree to the Terms of Service and Privacy Policy
                      </Label>
                    </div>
                  </div>

                  {/* Security Notice */}
                  <div className="p-4 bg-gray-50 rounded-lg flex items-center space-x-3">
                    <Lock className="w-5 h-5 text-green-600" />
                    <div className="text-sm text-gray-700">
                      Your payment information is encrypted and secure. We never
                      store credit card details.
                    </div>
                  </div>

                  {/* Submit Button */}
                  <Button size="lg" className="w-full btn-primary text-lg py-4">
                    <Heart className="mr-2 h-5 w-5" />
                    Complete Donation
                    {(amount || customAmount) && (
                      <span className="ml-2">
                        - ${amount || customAmount}
                        {donationType === "monthly" ? "/month" : ""}
                      </span>
                    )}
                  </Button>
                </CardContent>
              </Card>
            </div>

            {/* Sidebar */}
            <div className="space-y-8">
              {/* Donation Impact */}
              <Card className="border-0 shadow-lg">
                <CardHeader>
                  <CardTitle className="text-xl font-bold">
                    Your Impact
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-6">
                  {impactExamples.map((example, index) => (
                    <div key={index} className="flex items-start space-x-3">
                      <div className="w-10 h-10 bg-gradient-to-r from-empowerment-500 to-hope-500 rounded-lg flex items-center justify-center flex-shrink-0">
                        <example.icon className="w-5 h-5 text-white" />
                      </div>
                      <div className="space-y-1">
                        <div className="font-semibold text-empowerment-600">
                          {example.amount}
                        </div>
                        <div className="text-sm text-gray-600">
                          {example.impact}
                        </div>
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>

              {/* Other Ways to Give */}
              <Card className="border-0 shadow-lg">
                <CardHeader>
                  <CardTitle className="text-xl font-bold">
                    Other Ways to Give
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-3">
                    <div className="flex items-center space-x-3">
                      <Gift className="w-5 h-5 text-empowerment-600" />
                      <span className="text-sm">Corporate Partnerships</span>
                    </div>
                    <div className="flex items-center space-x-3">
                      <Users className="w-5 h-5 text-hope-600" />
                      <span className="text-sm">Volunteer Your Time</span>
                    </div>
                    <div className="flex items-center space-x-3">
                      <Award className="w-5 h-5 text-growth-600" />
                      <span className="text-sm">Legacy Giving</span>
                    </div>
                    <div className="flex items-center space-x-3">
                      <Heart className="w-5 h-5 text-strength-600" />
                      <span className="text-sm">Fundraise for Us</span>
                    </div>
                  </div>
                  <Button variant="outline" className="w-full">
                    Learn More
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </CardContent>
              </Card>

              {/* Donor Recognition */}
              <Card className="border-0 shadow-lg bg-gradient-to-br from-empowerment-50 to-hope-50">
                <CardContent className="p-6 text-center space-y-4">
                  <div className="w-12 h-12 bg-gradient-to-r from-empowerment-500 to-hope-500 rounded-full flex items-center justify-center mx-auto">
                    <Star className="w-6 h-6 text-white" />
                  </div>
                  <div className="space-y-2">
                    <h3 className="font-bold text-empowerment-800">
                      Donor Recognition
                    </h3>
                    <p className="text-sm text-empowerment-700">
                      Major donors are recognized in our annual report and on
                      our website (with permission).
                    </p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* Donor Testimonials */}
      <section className="py-20 bg-gray-50">
        <div className="container-custom">
          <div className="text-center space-y-4 mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold">
              What Our Donors Say
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Join a community of supporters who are passionate about women's
              empowerment.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <Card key={index} className="border-0 shadow-lg bg-white">
                <CardContent className="p-8">
                  <div className="space-y-6">
                    <div className="flex space-x-1">
                      {[...Array(5)].map((_, i) => (
                        <Star
                          key={i}
                          className="w-5 h-5 fill-current text-wisdom-500"
                        />
                      ))}
                    </div>
                    <blockquote className="text-gray-700 leading-relaxed">
                      "{testimonial.quote}"
                    </blockquote>
                    <div className="space-y-2">
                      <div className="font-semibold text-gray-900">
                        {testimonial.name}
                      </div>
                      <div className="text-empowerment-600 font-medium">
                        {testimonial.role}
                      </div>
                      <Badge
                        variant="secondary"
                        className="bg-empowerment-100 text-empowerment-800"
                      >
                        {testimonial.amount}
                      </Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Tax Information */}
      <section className="py-20 bg-white">
        <div className="container-custom">
          <div className="max-w-4xl mx-auto">
            <Card className="border-0 shadow-lg">
              <CardContent className="p-8">
                <div className="grid md:grid-cols-2 gap-8 items-center">
                  <div className="space-y-4">
                    <h3 className="text-2xl font-bold">
                      Tax-Deductible Donations
                    </h3>
                    <p className="text-gray-600 leading-relaxed">
                      Women's Foundation is a registered 501(c)(3) nonprofit
                      organization. Your donation is tax-deductible to the full
                      extent allowed by law.
                    </p>
                    <div className="space-y-2">
                      <div className="flex items-center space-x-2">
                        <CheckCircle className="w-5 h-5 text-green-600" />
                        <span className="text-sm">Tax ID: 12-3456789</span>
                      </div>
                      <div className="flex items-center space-x-2">
                        <CheckCircle className="w-5 h-5 text-green-600" />
                        <span className="text-sm">
                          Receipt provided for all donations
                        </span>
                      </div>
                      <div className="flex items-center space-x-2">
                        <CheckCircle className="w-5 h-5 text-green-600" />
                        <span className="text-sm">
                          GuideStar Gold Seal of Transparency
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="text-center">
                    <div className="w-24 h-24 bg-gradient-to-r from-empowerment-500 to-hope-500 rounded-full flex items-center justify-center mx-auto mb-4">
                      <Shield className="w-12 h-12 text-white" />
                    </div>
                    <div className="text-4xl font-bold text-empowerment-600 mb-2">
                      93%
                    </div>
                    <div className="text-gray-600">
                      of donations go directly to programs
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Donate;

// src/app/pages/donate/donate.component.ts
import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";
import { FormsModule } from "@angular/forms";
import {
  LucideAngularModule,
  Heart,
  DollarSign,
  Users,
  Gift,
  Shield,
  CreditCard,
  CheckCircle,
} from "lucide-angular";

@Component({
  selector: "app-donate",
  standalone: true,
  imports: [RouterLink, FormsModule, CommonModule],
  template: `
    <!-- Hero Section -->
    <section
      class="section-padding bg-gradient-to-br from-purple-50 via-white to-cyan-50"
    >
      <div class="container-max">
        <div class="text-center max-w-4xl mx-auto">
          <h1 class="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            Make a <span class="gradient-text">Difference</span>
          </h1>
          <p class="text-xl text-gray-600 mb-8">
            Your donation helps us empower women, break barriers, and create
            lasting change in communities around the world. Every contribution
            matters.
          </p>
        </div>
      </div>
    </section>

    <!-- Donation Impact -->
    <section class="section-padding bg-white">
      <div class="container-max">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Your <span class="gradient-text">Impact</span>
          </h2>
          <p class="text-lg text-gray-600 max-w-2xl mx-auto">
            See how your donation directly translates into opportunities and
            support for women.
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div class="card p-6 text-center animate-fade-in-up">
            <div
              class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-4"
            >
              <lucide-icon
                name="dollar-sign"
                class="w-8 h-8 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-2xl font-bold text-gray-900 mb-2">$25</h3>
            <p class="text-gray-600">
              Provides basic supplies for a woman in our skills training program
            </p>
          </div>

          <div
            class="card p-6 text-center animate-fade-in-up"
            style="animation-delay: 0.1s"
          >
            <div
              class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-4"
            >
              <lucide-icon
                name="dollar-sign"
                class="w-8 h-8 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-2xl font-bold text-gray-900 mb-2">$50</h3>
            <p class="text-gray-600">
              Funds a week of online education courses for a student
            </p>
          </div>

          <div
            class="card p-6 text-center animate-fade-in-up"
            style="animation-delay: 0.2s"
          >
            <div
              class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-4"
            >
              <lucide-icon
                name="dollar-sign"
                class="w-8 h-8 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-2xl font-bold text-gray-900 mb-2">$100</h3>
            <p class="text-gray-600">
              Supports a woman entrepreneur with business mentorship
            </p>
          </div>

          <div
            class="card p-6 text-center animate-fade-in-up"
            style="animation-delay: 0.3s"
          >
            <div
              class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-4"
            >
              <lucide-icon
                name="dollar-sign"
                class="w-8 h-8 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-2xl font-bold text-gray-900 mb-2">$250</h3>
            <p class="text-gray-600">
              Provides a full scholarship for our leadership development program
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Donation Form -->
    <section class="section-padding bg-gray-50">
      <div class="container-max">
        <div class="max-w-2xl mx-auto">
          <div class="card p-8">
            <div class="text-center mb-8">
              <h2 class="text-3xl font-bold text-gray-900 mb-4">
                Choose Your Donation Amount
              </h2>
              <p class="text-gray-600">
                Select an amount or enter a custom donation below.
              </p>
            </div>

            <form (ngSubmit)="handleDonate()" class="space-y-6">
              <!-- Donation Type -->
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-3"
                  >Donation Type</label
                >
                <div class="grid grid-cols-2 gap-4">
                  <label class="relative">
                    <input
                      type="radio"
                      name="donationType"
                      value="one-time"
                      [(ngModel)]="donationType"
                      class="sr-only"
                    />
                    <div
                      [class]="
                        donationType === 'one-time'
                          ? 'border-purple-500 bg-purple-50 text-purple-700'
                          : 'border-gray-300 text-gray-700'
                      "
                      class="border-2 rounded-lg p-4 text-center cursor-pointer transition-all"
                    >
                      <lucide-icon
                        name="gift"
                        class="w-6 h-6 mx-auto mb-2"
                      ></lucide-icon>
                      <span class="font-medium">One-time</span>
                    </div>
                  </label>
                  <label class="relative">
                    <input
                      type="radio"
                      name="donationType"
                      value="monthly"
                      [(ngModel)]="donationType"
                      class="sr-only"
                    />
                    <div
                      [class]="
                        donationType === 'monthly'
                          ? 'border-purple-500 bg-purple-50 text-purple-700'
                          : 'border-gray-300 text-gray-700'
                      "
                      class="border-2 rounded-lg p-4 text-center cursor-pointer transition-all"
                    >
                      <lucide-icon
                        name="heart"
                        class="w-6 h-6 mx-auto mb-2"
                      ></lucide-icon>
                      <span class="font-medium">Monthly</span>
                    </div>
                  </label>
                </div>
              </div>

              <!-- Amount Selection -->
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-3"
                  >Amount</label
                >
                <div class="grid grid-cols-4 gap-3 mb-4">
                  <label *ngFor="let amount of presetAmounts" class="relative">
                    <input
                      type="radio"
                      [value]="amount"
                      name="amount"
                      [(ngModel)]="selectedAmount"
                      class="sr-only"
                    />
                    <div
                      [class]="
                        selectedAmount === amount
                          ? 'border-purple-500 bg-purple-50 text-purple-700'
                          : 'border-gray-300 text-gray-700'
                      "
                      class="border-2 rounded-lg p-3 text-center cursor-pointer transition-all"
                    >
                      <span class="font-semibold">&#36;{{ amount }}</span>
                    </div>
                  </label>
                </div>
                <div class="relative">
                  <label
                    for="customAmount"
                    class="block text-sm text-gray-600 mb-2"
                    >Or enter custom amount:</label
                  >
                  <div class="relative">
                    <span
                      class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500"
                      >$</span
                    >
                    <input
                      type="number"
                      id="customAmount"
                      [(ngModel)]="customAmount"
                      name="customAmount"
                      (input)="onCustomAmountChange()"
                      placeholder="Enter amount"
                      class="w-full pl-8 pr-3 py-2 border border-gray-300 rounded-lg focus:ring-purple-500 focus:border-purple-500"
                    />
                  </div>
                </div>
              </div>

              <!-- Donor Information -->
              <div class="space-y-4">
                <h3 class="text-lg font-semibold text-gray-900">
                  Donor Information
                </h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label
                      for="firstName"
                      class="block text-sm font-medium text-gray-700 mb-1"
                      >First Name</label
                    >
                    <input
                      type="text"
                      id="firstName"
                      [(ngModel)]="donorInfo.firstName"
                      name="firstName"
                      required
                      class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-purple-500 focus:border-purple-500"
                    />
                  </div>
                  <div>
                    <label
                      for="lastName"
                      class="block text-sm font-medium text-gray-700 mb-1"
                      >Last Name</label
                    >
                    <input
                      type="text"
                      id="lastName"
                      [(ngModel)]="donorInfo.lastName"
                      name="lastName"
                      required
                      class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-purple-500 focus:border-purple-500"
                    />
                  </div>
                </div>
                <div>
                  <label
                    for="email"
                    class="block text-sm font-medium text-gray-700 mb-1"
                    >Email Address</label
                  >
                  <input
                    type="email"
                    id="email"
                    [(ngModel)]="donorInfo.email"
                    name="email"
                    required
                    class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-purple-500 focus:border-purple-500"
                  />
                </div>
              </div>

              <!-- Payment Security Notice -->
              <div class="bg-green-50 border border-green-200 rounded-lg p-4">
                <div class="flex items-center">
                  <lucide-icon
                    name="shield"
                    class="w-5 h-5 text-green-600 mr-2"
                  ></lucide-icon>
                  <span class="text-sm text-green-800 font-medium"
                    >Secure Payment</span
                  >
                </div>
                <p class="text-sm text-green-700 mt-1">
                  Your payment information is encrypted and secure. We never
                  store your payment details.
                </p>
              </div>

              <!-- Donate Button -->
              <button
                type="submit"
                class="w-full btn-primary btn-primary-gradient text-lg py-3"
              >
                <lucide-icon name="heart" class="w-5 h-5 mr-2"></lucide-icon>
                Donate {{ getDonationAmount() | currency }}
                {{ donationType === "monthly" ? "/month" : "" }}
              </button>
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- Why Donate -->
    <section class="section-padding bg-white">
      <div class="container-max">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Why <span class="gradient-text">Donate</span>?
          </h2>
          <p class="text-lg text-gray-600 max-w-2xl mx-auto">
            Your support helps us continue our vital work in empowering women
            worldwide.
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div class="text-center animate-fade-in-up">
            <div
              class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <lucide-icon
                name="users"
                class="w-8 h-8 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 mb-4">
              Direct Impact
            </h3>
            <p class="text-gray-600">
              95% of donations go directly to programs. Your money creates
              immediate, measurable change in women's lives.
            </p>
          </div>

          <div
            class="text-center animate-fade-in-up"
            style="animation-delay: 0.1s"
          >
            <div
              class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <lucide-icon
                name="check-circle"
                class="w-8 h-8 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 mb-4">
              Proven Results
            </h3>
            <p class="text-gray-600">
              Over 10 years of experience with documented success stories and
              transparent impact reporting.
            </p>
          </div>

          <div
            class="text-center animate-fade-in-up"
            style="animation-delay: 0.2s"
          >
            <div
              class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <lucide-icon
                name="shield"
                class="w-8 h-8 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 mb-4">
              Trusted Organization
            </h3>
            <p class="text-gray-600">
              Recognized by leading organizations and awarded for our commitment
              to transparency and effectiveness.
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Other Ways to Help -->
    <section class="section-padding bg-gray-50">
      <div class="container-max">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Other Ways to <span class="gradient-text">Help</span>
          </h2>
          <p class="text-lg text-gray-600 max-w-2xl mx-auto">
            Can't donate right now? There are other meaningful ways to support
            our mission.
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div class="card p-6 text-center">
            <h3 class="text-xl font-semibold text-gray-900 mb-4">Volunteer</h3>
            <p class="text-gray-600 mb-4">
              Share your skills and time to directly support our programs and
              participants.
            </p>
            <a
              routerLink="/contact"
              class="text-purple-600 font-medium hover:text-purple-700"
            >
              Learn More →
            </a>
          </div>

          <div class="card p-6 text-center">
            <h3 class="text-xl font-semibold text-gray-900 mb-4">
              Corporate Partnership
            </h3>
            <p class="text-gray-600 mb-4">
              Partner with us to create employee engagement programs and CSR
              initiatives.
            </p>
            <a
              routerLink="/contact"
              class="text-purple-600 font-medium hover:text-purple-700"
            >
              Partner with Us →
            </a>
          </div>

          <div class="card p-6 text-center">
            <h3 class="text-xl font-semibold text-gray-900 mb-4">
              Spread the Word
            </h3>
            <p class="text-gray-600 mb-4">
              Share our mission on social media and help us reach more
              supporters.
            </p>
            <a
              href="#"
              class="text-purple-600 font-medium hover:text-purple-700"
            >
              Share Now →
            </a>
          </div>
        </div>
      </div>
    </section>

    <!-- Thank You Message (if donated) -->
    <div
      *ngIf="showThankYou"
      class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50"
    >
      <div class="bg-white rounded-lg p-8 max-w-md w-full text-center">
        <div
          class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-4"
        >
          <lucide-icon name="heart" class="w-8 h-8 text-white"></lucide-icon>
        </div>
        <h3 class="text-2xl font-bold text-gray-900 mb-4">Thank You!</h3>
        <p class="text-gray-600 mb-6">
          Your generous donation will make a real difference in women's lives.
          You'll receive a confirmation email shortly.
        </p>
        <button
          (click)="showThankYou = false"
          class="btn-primary btn-primary-gradient"
        >
          Continue
        </button>
      </div>
    </div>
  `,
})
export class DonateComponent {
  readonly Heart = Heart;
  readonly DollarSign = DollarSign;
  readonly Users = Users;
  readonly Gift = Gift;
  readonly Shield = Shield;
  readonly CreditCard = CreditCard;
  readonly CheckCircle = CheckCircle;

  donationType: "one-time" | "monthly" = "one-time";
  selectedAmount: number | null = null;
  customAmount: number | null = null;
  presetAmounts = [25, 50, 100, 250];
  showThankYou = false;

  donorInfo = {
    firstName: "",
    lastName: "",
    email: "",
  };

  onCustomAmountChange() {
    if (this.customAmount) {
      this.selectedAmount = null;
    }
  }

  getDonationAmount(): number {
    return this.customAmount || this.selectedAmount || 0;
  }

  handleDonate() {
    const amount = this.getDonationAmount();
    if (
      amount > 0 &&
      this.donorInfo.firstName &&
      this.donorInfo.lastName &&
      this.donorInfo.email
    ) {
      // In a real application, this would integrate with a payment processor
      console.log("Processing donation:", {
        amount,
        type: this.donationType,
        donor: this.donorInfo,
      });

      this.showThankYou = true;

      // Reset form
      this.selectedAmount = null;
      this.customAmount = null;
      this.donorInfo = {
        firstName: "",
        lastName: "",
        email: "",
      };
    }
  }
}
