// src/pages/Home.tsx
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import {
  Heart,
  Users,
  Award,
  TrendingUp,
  BookOpen,
  Briefcase,
  Shield,
  Star,
  ArrowRight,
  Play,
  CheckCircle,
} from "lucide-react";

const Home = () => {
  const stats = [
    { number: "15K+", label: "Women Empowered", icon: Users },
    { number: "250+", label: "Programs Delivered", icon: Award },
    { number: "98%", label: "Success Rate", icon: TrendingUp },
    { number: "50+", label: "Partner Organizations", icon: Heart },
  ];

  const programs = [
    {
      title: "Education & Scholarships",
      description:
        "Providing access to quality education and financial support for women pursuing higher education.",
      icon: BookOpen,
      color: "empowerment",
      link: "/programs#education",
    },
    {
      title: "Career Development",
      description:
        "Professional skills training, job placement assistance, and career advancement programs.",
      icon: Briefcase,
      color: "hope",
      link: "/programs#career",
    },
    {
      title: "Health & Wellness",
      description:
        "Comprehensive healthcare access, mental health support, and wellness education programs.",
      icon: Shield,
      color: "growth",
      link: "/programs#health",
    },
  ];

  const testimonials = [
    {
      name: "Sarah Johnson",
      role: "Program Graduate",
      content:
        "This foundation changed my life. Through their education program, I was able to complete my degree and start my own business.",
      rating: 5,
    },
    {
      name: "Maria Rodriguez",
      role: "Career Development Participant",
      content:
        "The mentorship and career guidance I received helped me advance from entry-level to management in just two years.",
      rating: 5,
    },
    {
      name: "Jennifer Chen",
      role: "Leadership Program Alumni",
      content:
        "The leadership skills I learned here have made me a confident advocate for women's rights in my community.",
      rating: 5,
    },
  ];

  const achievements = [
    "15,000+ women successfully completed our programs",
    "98% employment rate among career program graduates",
    "500+ scholarships awarded to deserving students",
    "250+ successful business launches supported",
    "100+ leadership positions filled by our alumni",
  ];

  return (
    <div className="min-h-screen">
      <Header />

      {/* Hero Section */}
      <section className="hero-gradient">
        <div className="container-custom py-20 lg:py-28">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-8">
              <div className="space-y-4">
                <Badge
                  variant="secondary"
                  className="bg-empowerment-100 text-empowerment-800 hover:bg-empowerment-200"
                >
                  Empowering Women Since 2010
                </Badge>
                <h1 className="text-4xl lg:text-6xl font-bold leading-tight">
                  Empowering Women to
                  <span className="gradient-text"> Change the World</span>
                </h1>
                <p className="text-xl text-gray-600 leading-relaxed">
                  We believe every woman deserves the opportunity to reach her
                  full potential. Through education, leadership development, and
                  community support, we're building a brighter future together.
                </p>
              </div>

              <div className="flex flex-col sm:flex-row gap-4">
                <Link to="/donate">
                  <Button size="lg" className="btn-primary text-lg px-8 py-4">
                    <Heart className="mr-2 h-5 w-5" />
                    Make a Donation
                  </Button>
                </Link>
                <Link to="/programs">
                  <Button
                    size="lg"
                    variant="outline"
                    className="text-lg px-8 py-4 border-2 border-empowerment-300 text-empowerment-700 hover:bg-empowerment-50"
                  >
                    <Play className="mr-2 h-5 w-5" />
                    Explore Programs
                  </Button>
                </Link>
              </div>
            </div>

            <div className="relative">
              <div className="aspect-square rounded-3xl overflow-hidden bg-gradient-to-br from-empowerment-100 to-hope-100 p-8">
                <div className="w-full h-full bg-gradient-to-br from-empowerment-200 to-hope-200 rounded-2xl flex items-center justify-center">
                  <div className="text-center space-y-4">
                    <div className="w-24 h-24 bg-white rounded-full flex items-center justify-center mx-auto shadow-lg">
                      <Heart className="w-12 h-12 text-empowerment-600" />
                    </div>
                    <h3 className="text-2xl font-bold text-gray-800">
                      15,000+
                    </h3>
                    <p className="text-gray-600 font-medium">
                      Lives Transformed
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 bg-white">
        <div className="container-custom">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <div key={index} className="text-center space-y-4">
                <div className="w-16 h-16 bg-gradient-to-r from-empowerment-500 to-hope-500 rounded-full flex items-center justify-center mx-auto">
                  <stat.icon className="w-8 h-8 text-white" />
                </div>
                <div>
                  <div className="text-3xl lg:text-4xl font-bold text-gray-900">
                    {stat.number}
                  </div>
                  <div className="text-gray-600 font-medium">{stat.label}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Programs Section */}
      <section className="py-20 bg-gray-50">
        <div className="container-custom">
          <div className="text-center space-y-4 mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold">
              Our Impact Programs
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              We offer comprehensive programs designed to address the unique
              challenges women face and provide them with the tools they need to
              succeed.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {programs.map((program, index) => (
              <Card
                key={index}
                className="card-hover border-0 shadow-lg bg-white"
              >
                <CardContent className="p-8">
                  <div className="space-y-6">
                    <div
                      className={`w-16 h-16 bg-gradient-to-r from-${program.color}-500 to-${program.color}-600 rounded-xl flex items-center justify-center`}
                    >
                      <program.icon className="w-8 h-8 text-white" />
                    </div>
                    <div className="space-y-3">
                      <h3 className="text-xl font-bold">{program.title}</h3>
                      <p className="text-gray-600 leading-relaxed">
                        {program.description}
                      </p>
                    </div>
                    <Link
                      to={program.link}
                      className="inline-flex items-center text-empowerment-600 hover:text-empowerment-700 font-semibold"
                    >
                      Learn More <ArrowRight className="ml-2 h-4 w-4" />
                    </Link>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Achievements Section */}
      <section className="py-20 bg-white">
        <div className="container-custom">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-8">
              <div className="space-y-4">
                <h2 className="text-3xl lg:text-4xl font-bold">
                  Our Achievements
                </h2>
                <p className="text-xl text-gray-600">
                  Over the years, we've made significant impact in the lives of
                  women and their communities. Here are some of our proudest
                  achievements.
                </p>
              </div>

              <div className="space-y-4">
                {achievements.map((achievement, index) => (
                  <div key={index} className="flex items-start space-x-3">
                    <CheckCircle className="w-6 h-6 text-growth-500 mt-0.5 flex-shrink-0" />
                    <span className="text-gray-700">{achievement}</span>
                  </div>
                ))}
              </div>

              <Link to="/impact">
                <Button className="btn-secondary">
                  View Full Impact Report
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </Link>
            </div>

            <div className="grid grid-cols-2 gap-6">
              <div className="space-y-6">
                <Card className="p-6 bg-gradient-to-br from-empowerment-50 to-empowerment-100 border-empowerment-200">
                  <div className="text-center">
                    <div className="text-3xl font-bold text-empowerment-700">
                      250+
                    </div>
                    <div className="text-empowerment-600 font-medium">
                      Programs
                    </div>
                  </div>
                </Card>
                <Card className="p-6 bg-gradient-to-br from-growth-50 to-growth-100 border-growth-200">
                  <div className="text-center">
                    <div className="text-3xl font-bold text-growth-700">
                      50+
                    </div>
                    <div className="text-growth-600 font-medium">Countries</div>
                  </div>
                </Card>
              </div>
              <div className="space-y-6 mt-8">
                <Card className="p-6 bg-gradient-to-br from-hope-50 to-hope-100 border-hope-200">
                  <div className="text-center">
                    <div className="text-3xl font-bold text-hope-700">98%</div>
                    <div className="text-hope-600 font-medium">
                      Success Rate
                    </div>
                  </div>
                </Card>
                <Card className="p-6 bg-gradient-to-br from-wisdom-50 to-wisdom-100 border-wisdom-200">
                  <div className="text-center">
                    <div className="text-3xl font-bold text-wisdom-700">
                      24/7
                    </div>
                    <div className="text-wisdom-600 font-medium">Support</div>
                  </div>
                </Card>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-gray-50">
        <div className="container-custom">
          <div className="text-center space-y-4 mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold">Success Stories</h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Hear from the amazing women whose lives have been transformed
              through our programs.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <Card
                key={index}
                className="card-hover border-0 shadow-lg bg-white"
              >
                <CardContent className="p-8">
                  <div className="space-y-6">
                    <div className="flex space-x-1">
                      {[...Array(testimonial.rating)].map((_, i) => (
                        <Star
                          key={i}
                          className="w-5 h-5 fill-current text-wisdom-500"
                        />
                      ))}
                    </div>
                    <blockquote className="text-gray-700 leading-relaxed">
                      "{testimonial.content}"
                    </blockquote>
                    <div className="pt-4 border-t">
                      <div className="font-semibold text-gray-900">
                        {testimonial.name}
                      </div>
                      <div className="text-gray-600">{testimonial.role}</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-empowerment-600 to-hope-600 text-white">
        <div className="container-custom text-center">
          <div className="max-w-3xl mx-auto space-y-8">
            <h2 className="text-3xl lg:text-4xl font-bold">
              Ready to Make a Difference?
            </h2>
            <p className="text-xl opacity-90">
              Join us in empowering women and creating lasting change in
              communities around the world. Every contribution matters, and
              together we can build a brighter future.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/donate">
                <Button
                  size="lg"
                  className="bg-white text-empowerment-600 hover:bg-gray-100 text-lg px-8 py-4"
                >
                  <Heart className="mr-2 h-5 w-5" />
                  Donate Today
                </Button>
              </Link>
              <Link to="/contact">
                <Button
                  size="lg"
                  variant="outline"
                  className="border-white text-white hover:bg-white/10 text-lg px-8 py-4"
                >
                  Get Involved
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Home;

// src/app/pages/home/home.component.ts
import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";
import { CommonModule } from "@angular/common";

@Component({
  selector: "app-home",
  standalone: true,
  imports: [RouterLink, CommonModule],
  template: `
    <!-- Hero Section -->
    <section
      class="py-12 sm:py-16 lg:py-20 xl:py-24 px-4 sm:px-6 lg:px-8 bg-gradient-to-br from-pink-50 via-white to-rose-50"
    >
      <div class="max-w-7xl mx-auto">
        <div
          class="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12 xl:gap-16 items-center"
        >
          <!-- Content -->
          <div class="order-2 lg:order-1 text-center lg:text-left">
            <h1
              class="text-3xl sm:text-4xl md:text-5xl lg:text-6xl xl:text-7xl font-bold leading-tight mb-6 lg:mb-8"
            >
              Empowering
              <span
                class="block sm:inline bg-gradient-to-r from-pink-500 via-pink-400 to-rose-400 bg-clip-text text-transparent"
                >Women</span
              >
              <span class="block sm:inline">to Change the World</span>
            </h1>
            <p
              class="text-base sm:text-lg lg:text-xl text-gray-600 mb-8 lg:mb-10 max-w-2xl mx-auto lg:mx-0"
            >
              Join our mission to create opportunities, break barriers, and
              build a more equitable future for women everywhere through
              education, support, and community building.
            </p>
            <div
              class="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start"
            >
              <a
                routerLink="/donate"
                class="inline-flex items-center justify-center px-6 lg:px-8 py-3 lg:py-4 text-base lg:text-lg font-semibold text-white bg-gradient-to-r from-pink-500 to-pink-400 rounded-lg hover:from-pink-600 hover:to-pink-500 transform hover:scale-105 transition-all duration-200 shadow-lg hover:shadow-xl animate-pink-glow"
              >
                <span class="mr-2">💖</span>
                Make a Donation
              </a>
              <a
                routerLink="/programs"
                class="inline-flex items-center justify-center px-6 lg:px-8 py-3 lg:py-4 text-base lg:text-lg font-semibold text-gray-700 bg-white border-2 border-pink-300 rounded-lg hover:bg-pink-50 hover:border-pink-400 transition-all duration-200"
              >
                Learn More
                <span class="ml-2">→</span>
              </a>
            </div>
          </div>

          <!-- Hero Image -->
          <div class="order-1 lg:order-2 relative">
            <div
              class="relative z-10 bg-white rounded-2xl shadow-2xl p-4 sm:p-6 lg:p-8 transform hover:scale-105 transition-transform duration-300 border border-pink-100"
            >
              <img
                src="https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80"
                alt="Empowered women"
                class="w-full h-48 sm:h-64 lg:h-80 xl:h-96 object-cover rounded-xl"
              />
            </div>
            <!-- Floating decorative elements -->
            <div
              class="absolute -top-4 -left-4 w-16 h-16 sm:w-20 sm:h-20 lg:w-24 lg:h-24 bg-gradient-to-r from-pink-400 to-rose-400 rounded-full opacity-20 animate-pulse"
            ></div>
            <div
              class="absolute -bottom-4 -right-4 w-20 h-20 sm:w-24 sm:h-24 lg:w-32 lg:h-32 bg-gradient-to-r from-rose-400 to-pink-300 rounded-full opacity-20 animate-pulse"
              style="animation-delay: 1s"
            ></div>
          </div>
        </div>
      </div>
    </section>

    <!-- Stats Section -->
    <section class="py-12 sm:py-16 lg:py-20 px-4 sm:px-6 lg:px-8 bg-white">
      <div class="max-w-7xl mx-auto">
        <div class="grid grid-cols-2 lg:grid-cols-4 gap-6 lg:gap-8">
          <div
            *ngFor="let stat of stats; let i = index"
            class="text-center transform hover:scale-105 transition-transform duration-200"
            [style.animation-delay]="i * 0.1 + 's'"
          >
            <div
              class="w-12 h-12 sm:w-16 sm:h-16 lg:w-20 lg:h-20 bg-gradient-to-r from-pink-500 to-pink-400 rounded-full flex items-center justify-center mx-auto mb-3 sm:mb-4 lg:mb-6 shadow-lg shadow-pink-200"
            >
              <span
                class="text-white text-lg sm:text-xl lg:text-2xl xl:text-3xl"
                >{{ stat.icon }}</span
              >
            </div>
            <h3
              class="text-xl sm:text-2xl lg:text-3xl xl:text-4xl font-bold text-gray-900 mb-1 sm:mb-2"
            >
              {{ stat.number }}
            </h3>
            <p
              class="text-xs sm:text-sm lg:text-base text-gray-600 leading-tight"
            >
              {{ stat.label }}
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Programs Preview -->
    <section class="py-12 sm:py-16 lg:py-20 px-4 sm:px-6 lg:px-8 bg-pink-50">
      <div class="max-w-7xl mx-auto">
        <div class="text-center mb-10 sm:mb-12 lg:mb-16">
          <h2
            class="text-2xl sm:text-3xl lg:text-4xl xl:text-5xl font-bold text-gray-900 mb-4 lg:mb-6"
          >
            Our
            <span
              class="bg-gradient-to-r from-pink-500 via-pink-400 to-rose-400 bg-clip-text text-transparent"
              >Programs</span
            >
          </h2>
          <p
            class="text-base sm:text-lg lg:text-xl text-gray-600 max-w-3xl mx-auto"
          >
            Discover how we're making a difference through our comprehensive
            programs designed to empower women at every stage of their journey.
          </p>
        </div>

        <div
          class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8"
        >
          <div
            *ngFor="let program of programs; let i = index"
            class="bg-white rounded-xl shadow-md overflow-hidden hover:shadow-xl transform hover:-translate-y-2 transition-all duration-300 p-6 lg:p-8 border border-pink-100"
            [style.animation-delay]="i * 0.1 + 's'"
          >
            <div
              class="w-12 h-12 sm:w-16 sm:h-16 bg-gradient-to-r from-pink-500 to-pink-400 rounded-xl flex items-center justify-center mb-4 lg:mb-6 shadow-lg shadow-pink-200"
            >
              <span class="text-white text-lg sm:text-xl lg:text-2xl">{{
                program.icon
              }}</span>
            </div>
            <h3
              class="text-lg sm:text-xl lg:text-2xl font-semibold text-gray-900 mb-3 lg:mb-4"
            >
              {{ program.title }}
            </h3>
            <p
              class="text-sm sm:text-base text-gray-600 mb-4 lg:mb-6 leading-relaxed"
            >
              {{ program.description }}
            </p>
            <a
              routerLink="/programs"
              class="inline-flex items-center text-pink-600 font-semibold hover:text-pink-700 transition-colors duration-150 text-sm sm:text-base"
            >
              Learn More
              <span class="ml-1">→</span>
            </a>
          </div>
        </div>
      </div>
    </section>

    <!-- Testimonials -->
    <section class="py-12 sm:py-16 lg:py-20 px-4 sm:px-6 lg:px-8 bg-white">
      <div class="max-w-7xl mx-auto">
        <div class="text-center mb-10 sm:mb-12 lg:mb-16">
          <h2
            class="text-2xl sm:text-3xl lg:text-4xl xl:text-5xl font-bold text-gray-900 mb-4 lg:mb-6"
          >
            Stories of
            <span
              class="bg-gradient-to-r from-pink-500 via-pink-400 to-rose-400 bg-clip-text text-transparent"
              >Impact</span
            >
          </h2>
          <p
            class="text-base sm:text-lg lg:text-xl text-gray-600 max-w-3xl mx-auto"
          >
            Hear from the incredible women whose lives have been transformed
            through our programs.
          </p>
        </div>

        <div
          class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8"
        >
          <div
            *ngFor="let testimonial of testimonials; let i = index"
            class="bg-white rounded-xl shadow-md p-6 lg:p-8 hover:shadow-xl transform hover:-translate-y-1 transition-all duration-300 border border-pink-100"
            [style.animation-delay]="i * 0.1 + 's'"
          >
            <div class="flex items-center mb-4 lg:mb-6">
              <div class="flex text-pink-400 mb-2">
                <span
                  *ngFor="let star of [1, 2, 3, 4, 5]"
                  class="text-lg sm:text-xl"
                  >💖</span
                >
              </div>
            </div>
            <p
              class="text-sm sm:text-base text-gray-600 mb-4 lg:mb-6 italic leading-relaxed"
            >
              "{{ testimonial.quote }}"
            </p>
            <div class="flex items-center">
              <img
                [src]="testimonial.image"
                [alt]="testimonial.name"
                class="w-10 h-10 sm:w-12 sm:h-12 rounded-full object-cover mr-3 sm:mr-4 border-2 border-pink-200"
              />
              <div>
                <h4 class="text-sm sm:text-base font-semibold text-gray-900">
                  {{ testimonial.name }}
                </h4>
                <p class="text-xs sm:text-sm text-pink-600 font-medium">
                  {{ testimonial.role }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Call to Action -->
    <section
      class="py-12 sm:py-16 lg:py-20 px-4 sm:px-6 lg:px-8 bg-gradient-to-r from-pink-500 to-pink-400 text-white"
    >
      <div class="max-w-4xl mx-auto text-center">
        <h2
          class="text-2xl sm:text-3xl lg:text-4xl xl:text-5xl font-bold mb-4 lg:mb-6"
        >
          Ready to Make a Difference?
        </h2>
        <p
          class="text-base sm:text-lg lg:text-xl mb-8 lg:mb-10 opacity-90 leading-relaxed"
        >
          Join thousands of supporters who are helping us create a world where
          every woman has the opportunity to reach her full potential.
        </p>
        <div
          class="flex flex-col sm:flex-row gap-4 justify-center max-w-lg mx-auto"
        >
          <a
            routerLink="/donate"
            class="inline-flex items-center justify-center px-6 lg:px-8 py-3 lg:py-4 text-base lg:text-lg font-semibold bg-white text-pink-600 rounded-lg hover:bg-pink-50 transform hover:scale-105 transition-all duration-200 shadow-lg"
          >
            <span class="mr-2">💖</span>
            Donate Now
          </a>
          <a
            routerLink="/contact"
            class="inline-flex items-center justify-center px-6 lg:px-8 py-3 lg:py-4 text-base lg:text-lg font-semibold border-2 border-white text-white rounded-lg hover:bg-white hover:text-pink-600 transition-all duration-200"
          >
            Get Involved
            <span class="ml-2">→</span>
          </a>
        </div>
      </div>
    </section>
  `,
})
export class HomeComponent {
  stats = [
    { icon: "👥", number: "10,000+", label: "Women Empowered" },
    { icon: "🌍", number: "25", label: "Countries Reached" },
    { icon: "💼", number: "3,847", label: "Jobs Created" },
    { icon: "🏆", number: "95%", label: "Success Rate" },
  ];

  programs = [
    {
      icon: "📚",
      title: "Education & Skills",
      description:
        "Providing educational opportunities and skill development programs to help women build successful careers and achieve financial independence.",
    },
    {
      icon: "👥",
      title: "Community Support",
      description:
        "Building strong networks and support systems that connect women, foster mentorship, and create lasting bonds within our community.",
    },
    {
      icon: "📊",
      title: "Leadership Development",
      description:
        "Cultivating the next generation of women leaders through mentorship, training, and opportunities to make meaningful impact in their communities.",
    },
  ];

  testimonials = [
    {
      quote:
        "The Women's Foundation gave me the tools and confidence I needed to start my own business. I'm now employing 5 other women in my community.",
      name: "Sarah Johnson",
      role: "Entrepreneur",
      image:
        "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80",
    },
    {
      quote:
        "Through their leadership program, I found my voice and now serve on the city council. This foundation changes lives.",
      name: "Maria Rodriguez",
      role: "City Council Member",
      image:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80",
    },
    {
      quote:
        "The education programs helped me complete my degree while working full-time. I'm now a software engineer at a tech company.",
      name: "Jennifer Chen",
      role: "Software Engineer",
      image:
        "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80",
    },
  ];
}
